insert into categories(category_name)
     values("Arts and Craft"),
     ("automotive"),
     ("baby"),
     ("beauty Products"),
     ("books"),
     ("computers"),
     ("electronics"),
     ("women"),
     ("men"),
     ("girl"),
     ("boy"),
     ("health Products"),
     ("home Products"),
     ("industrial"),
     ("agro Products"),
     ("food"),
     ("animals"),
     ("services"),
     ("school"),
     ("cars"),
     ("games");