# Generated by Django 2.2.3 on 2019-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', null=True, unique=True),
        ),
    ]
