# Generated by Django 2.2.3 on 2019-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190902_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/categories'),
        ),
    ]
