# Generated by Django 2.2.3 on 2019-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190902_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_and_prod_default_pic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
