# Generated by Django 2.2.3 on 2019-09-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cat_and_prod_default_pic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat_and_Prod_default_pic',
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products'),
        ),
    ]
