# Generated by Django 2.2.3 on 2019-09-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
